try {
    hello ();
} catch (error) {
    console.log(error);
}

// ejemplo 2

try {
    onotherFn();
} catch {
    console.log("esto es un error")
}